name: Validate

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            python: "3.9"
          - os: ubuntu-latest
            python: "3.10"
          - os: ubuntu-latest
            python: "3.11"
          - os: macos-latest
            python: "3.12"
          - os: ubuntu-latest
            python: "3.13"
          - os: ubuntu-latest
            python: "3.14"
          - os: windows-latest
            python: "3.13"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python }}
      - name: Run tests
        run: python -m unittest discover -s tests -v
